version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_search
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:latest
    container_name: neo4j_search
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - neo4j_data:/data

volumes:
  mongo_data:
  neo4j_data:
